#ifndef SYSCALLTABLE_H
#define SYSCALLTABLE_H

//C library must be compatible with these numbers.
enum
{
    SYS_exit = 1,
    SYS_fork = 2,
    SYS_read = 3,
    SYS_write = 4,
    SYS_open = 5,
    SYS_close = 6,
    SYS_unlink = 10,
    SYS_execve = 11,
    SYS_chdir = 12,
    SYS_lseek = 19,
    SYS_getpid = 20,
    SYS_mount = 21,
    SYS_unmount = 22,
    SYS_kill = 37,
    SYS_mkdir = 39,
    SYS_rmdir = 40,
    SYS_brk = 45,
    SYS_ioctl = 54,
    SYS_mmap = 90,
    SYS_munmap = 91,
    SYS_ftruncate = 93,
    SYS_stat = 106,
    SYS_fstat = 108,
    SYS_wait4 = 114,
    SYS_llseek = 140,
    SYS_select = 142,
    SYS_readv = 145,
    SYS_writev = 146,
    SYS_nanosleep = 162,
    SYS_rt_sigaction = 174,
    SYS_getcwd = 183,
    SYS_mmap2 = 192,
    SYS_getdents64 = 220,
    SYS_set_thread_area = 243,
    SYS_exit_group = 252,
    SYS_set_tid_address = 258,

    SYS_socket = 359,
    SYS_socketpair = 360,
    SYS_bind = 361,
    SYS_connect = 362,
    SYS_listen = 363,
    SYS_accept4 = 364,
    SYS_getsockopt = 365,
    SYS_setsockopt = 366,
    SYS_getsockname = 367,
    SYS_getpeername = 368,
    SYS_sendto = 369,
    SYS_sendmsg = 370,
    SYS_recvfrom = 371,
    SYS_recvmsg = 372,
    SYS_shutdown = 373,

    SYS_statx = 383,

    SYS_shmget = 395,
    SYS_shmctl = 396,
    SYS_shmat = 397,
    SYS_shmdt = 398,

    SYS_clock_gettime64 = 403,
    SYS_clock_settime64 = 404,
    SYS_clock_getres64 = 406,

    
    //soso specific
    //TODO: make them linux compatible and delete below
    //we can keep some of them like SYS_getprocs vs.
    //but openpt and ptsname really should be implemented by /dev/ptmx
    
    SYS_posix_openpt = 3001,
    SYS_ptsname_r,
    SYS_accept,
    SYS_getthreads,
    SYS_getprocs,
    SYS_shm_open,
    SYS_execute,
    SYS_execute_on_tty,
    SYS_soso_read_dir,
    SYS_sleep_ms,
    SYS_get_uptime_ms,
    SYS_manage_message,
    SYS_manage_pipe,
    SYS_wait,
    SYS_printk,

    SYSCALL_COUNT
};

enum OldSyscall
{
    SYS_old_open,
    SYS_old_close,
    SYS_old_read,
    SYS_old_write,
    SYS_old_lseek,
    SYS_old_stat,
    SYS_old_fstat,
    SYS_old_ioctl,
    SYS_old_exit,
    SYS_old_sbrk,
    SYS_old_fork,
    SYS_old_getpid,

    SYS_old_execute,
    SYS_old_execve,
    SYS_old_wait,
    SYS_old_kill,
    SYS_old_mount,
    SYS_old_unmount,
    SYS_old_mkdir,
    SYS_old_rmdir,
    SYS_old_getdents64,
    SYS_old_getcwd,
    SYS_old_chdir,
    SYS_old_manage_pipe,
    SYS_old_soso_read_dir,
    SYS_old_get_uptime_ms,
    SYS_old_sleep_ms,
    SYS_old_execute_on_tty,
    SYS_old_manage_message,
    SYS_old_rt_sigaction,

    SYS_old_mmap,
    SYS_old_munmap,
    SYS_old_shm_open,
    SYS_old_unlink,
    SYS_old_ftruncate,
    SYS_old_posix_openpt,
    SYS_old_ptsname_r,

    SYS_old_printk,

    SYS_old_readv,
    SYS_old_writev,
    SYS_old_set_thread_area,
    SYS_old_set_tid_address,
    SYS_old_exit_group,
    SYS_old_llseek,
    SYS_old_select,
    SYS_old_statx,
    SYS_old_wait4,
    SYS_old_clock_gettime64,
    SYS_old_clock_settime64,
    SYS_old_clock_getres64,
    
    SYS_old_shmget,
    SYS_old_shmat,
    SYS_old_shmdt,
    SYS_old_shmctl,

    SYS_old_socket,
    SYS_old_socketpair,
    SYS_old_bind,
    SYS_old_connect,
    SYS_old_listen,
    SYS_old_accept4,
    SYS_old_getsockopt,
    SYS_old_setsockopt,
    SYS_old_getsockname,
    SYS_old_getpeername,
    SYS_old_sendto,
    SYS_old_sendmsg,
    SYS_old_recvfrom,
    SYS_old_recvmsg,
    SYS_old_shutdown,
    SYS_old_accept,

    SYS_old_nanosleep,
    SYS_old_getthreads,
    SYS_old_getprocs,

    SYSCALL_COUNT_old
};

#endif // SYSCALLTABLE_H
