#!/bin/bash

CLANG_BIN="/usr/lib/llvm-19/bin/clang"
SYSROOT="/opt/soso-toolchain/i386-soso/sys-root"
LINKERSCRIPT="$SYSROOT/soso.ld"
BUILTINS="/usr/lib/llvm-19/lib/clang/19/lib/linux/libclang_rt.builtins-i386.a"
CRT_PATH="$SYSROOT/lib"
LLD="/usr/bin/ld.lld"

# If compiling only, skip link flags
if [[ "$@" == *"-c"* ]]; then
  exec "$CLANG_BIN" \
    -m32 \
    --sysroot="$SYSROOT" \
    "$@"
  exit
fi

# Full link
exec "$CLANG_BIN" \
  -m32 \
  --sysroot="$SYSROOT" \
  -nostdlib \
  -fuse-ld=lld \
  -Wno-unused-command-line-argument \
  -Wl,-T,"$LINKERSCRIPT" \
  -Wl,--gc-sections \
  -Wl,--build-id=none \
  -Wl,-z,max-page-size=4096 \
  "$CRT_PATH/crt1.o" \
  "$CRT_PATH/crti.o" \
  "$@" \
  "$CRT_PATH/crtn.o" \
  "$CRT_PATH/libc.a" \
  "$BUILTINS"
